const SHNOPIA_DEFAULTS = [

    // NOUVEAU CODE (Glitch FX)
    "SLE8:eyJtIjoiRlgiLCJrIjozMjAwLCJ0IjowLCJoIjowLCJzIjoxMDAsInYiOjEwMCwiZCI6MTAwLCJmbSI6MzMsInNjIjozLCJzcyI6NTAsInAxIjo1NiwicDIiOjAsIm1tIjotMSwidG8iOnRydWUsInRzIjoiUm9zc2lnbm9sIEdyaXAgVmliZSBDb2RpbmcgLSBDb2RlZCB3aXRoIEdvb2dsZSBHZW1pbmkgUFJPIDMiLCJ0c3oiOjI1LCJ0c3AiOjEsInRjIjoiI2ZmZmZmZiIsInRmIjoiJ0JsYWNrIE9wcyBPbmUnLCBjdXJzaXZlIiwidGUiOiJHTElUQ0giLCJ0ZmwiOjEwMCwiZ2wiOjEsIndsIjowLCJubCI6MH0=",

    // Code 1 (Fire)
    "SLE8:eyJtIjoiRlgiLCJrIjozMjAwLCJ0IjowLCJoIjowLCJzIjoxMDAsInYiOjEwMCwiZCI6MTAwLCJmbSI6Miwic2MiOjMsInNzIjo1MCwicDEiOjI3LCJwMiI6MCwibW0iOi0xLCJ0byI6dHJ1ZSwidHMiOiJGaXJlIiwidHN6Ijo1NCwidHNwIjoxLCJ0YyI6IiNmZmZmZmYiLCJ0ZiI6IidDcmVlcHN0ZXInLCBjdXJzaXZlIiwidGUiOiJTVFJPS0UiLCJ0ZmwiOjUwLCJnbCI6MSwid2wiOjAsIm5sIjowfQ==",

    // Code 2
    "SLE8:eyJtIjoiRlgiLCJrIjozMjAwLCJ0IjowLCJoIjowLCJzIjoxMDAsInYiOjEwMCwiZCI6MTAwLCJmbSI6MTYsInNjIjozLCJzcyI6NTAsInAxIjo1NCwicDIiOjAsIm1tIjotMSwidG8iOnRydWUsInRzIjoiUm9zc2lnbm9sIEdyaXAgVmliZSBDb2RpbmcgLSBDb2RlZCB3aXRoIEdvb2dsZSBHZW1pbmkgUFJPIDMiLCJ0c3oiOjIyLCJ0c3AiOjEsInRjIjoiI2ZmZmZmZiIsInRmIjoiJ0JsYWNrIE9wcyBPbmUnLCBjdXJzaXZlIiwidGUiOiJTVFJPS0UiLCJ0ZmwiOjUwLCJnbCI6MSwid2wiOjAsIm5sIjowfQ==",

    // Code 3
    "SLE8:eyJtIjoiRlgiLCJrIjozMjAwLCJ0IjowLCJoIjowLCJzIjoxMDAsInYiOjEwMCwiZCI6MTAwLCJmbSI6MjksInNjIjozLCJzcyI6NTAsInAxIjoxMDAsInAyIjoyNywibW0iOjAsInRvIjpmYWxzZSwidHMiOiJSb3NzaWdub2wgR3JpcCBWaWJlIENvZGluZyAtIENvZGVkIHdpdGggR29vZ2xlIEdlbWluaSBQUk8gMyIsInRzeiI6MjIsInRzcCI6MSwidGMiOiIjZmZmZmZmIiwidGYiOiInQmxhY2sgT3BzIE9uZScsIGN1cnNpdmUiLCJ0ZSI6IlNUUk9LRSIsInRmbCI6NTAsImdsIjoyLCJ3bCI6MCwibmwiOjB9",

    // Code 4
    "SLE8:eyJtIjoiRlgiLCJrIjozMjAwLCJ0IjowLCJoIjowLCJzIjoxMDAsInYiOjEwMCwiZCI6MTAwLCJmbSI6MzEsInNjIjozLCJzcyI6MjUsInAxIjo1NSwicDIiOjAsIm1tIjotMSwidG8iOnRydWUsInRzIjoiUm9zc2lnbm9sIEdyaXAgVmliZSBDb2RpbmcgLSBDb2RlZCB3aXRoIEdvb2dsZSBHZW1pbmkgUFJPIDMiLCJ0c3oiOjIyLCJ0c3AiOjEsInRjIjoiI2ZmZmZmZiIsInRmIjoiJ0JsYWNrIE9wcyBPbmUnLCBjdXJzaXZlIiwidGUiOiJTSEFLRSIsInRmbCI6NTAsImdsIjoyLCJ3bCI6MCwibmwiOjB9",

    // Code 5
    "SLE8:eyJtIjoiRlgiLCJrIjozMjAwLCJ0IjowLCJoIjowLCJzIjoxMDAsInYiOjEwMCwiZCI6MTAwLCJmbSI6MTksInNjIjo0LCJzcyI6NTAsInAxIjo0NSwicDIiOjAsIm1tIjotMSwidG8iOnRydWUsInRzIjoiRWxldmF0b3IiLCJ0c3oiOjI5LCJ0c3AiOjEsInRjIjoiI2ZmZmZmZiIsInRmIjoiJ0JlYmFzIE5ldWUnLCBzYW5zLXNlcmlmIiwidGUiOiJTVFJPS0UiLCJ0ZmwiOjUwLCJnbCI6MSwid2wiOjAsIm5sIjowfQ==",

    // Code 6
    "SLE8:eyJtIjoiRlgiLCJrIjozMjAwLCJ0IjowLCJoIjowLCJzIjoxMDAsInYiOjEwMCwiZCI6MTAwLCJmbSI6MzIsInNjIjo0LCJzcyI6MTMsInAxIjo1MCwicDIiOjUwLCJtbSI6NCwidG8iOmZhbHNlLCJ0cyI6IlJvc3NpZ25vbCBHcmlwIFZpYmUgQ29kaW5nIC0gQ29kZWQgd2l0aCBHb29nbGUgR2VtaW5pIFBSTyAzIiwidHN6IjoyMiwidHNwIjoxLCJ0YyI6IiNmZmZmZmYiLCJ0ZiI6IidCbGFjayBPcHMgT25lJywgY3Vyc2l2ZSIsInRlIjoiU1RST0tFIiwidGZsIjo1MCwiZ2wiOjQsIndsIjowLCJubCI6MH0=",

    // Code 7 (Green Screen)
    "SLE8:eyJtIjoiV0hFRUwiLCJrIjozMjAwLCJ0IjowLCJoIjoxMjAsInMiOjEwMCwidiI6MTAwLCJkIjoxMDAsImZtIjowLCJzYyI6Mywic3MiOjI1LCJwMSI6NTUsInAyIjowLCJtbSI6LTEsInRvIjp0cnVlLCJ0cyI6IkdyZWVuIFNjcmVlbiIsInRzeiI6MTMsInRzcCI6MCwidGMiOiIjZmZmZmZmIiwidGYiOiInUHJlc3MgU3RhcnQgMlAnLCBjdXJzaXZlIiwidGUiOiJTSEFLRSIsInRmbCI6MTAwLCJnbCI6Miwid2wiOjAsIm5sIjowfQ==",

    // Code 8 (Vortex) - Ajout des guillemets et virgule
    "SLE8:eyJtIjoiRlgiLCJrIjozMjAwLCJ0IjowLCJoIjowLCJzIjoxMDAsInYiOjEwMCwiZCI6MTAwLCJmbSI6NDAsInNjIjo0LCJzcyI6NTAsInAxIjo1MCwicDIiOjUwLCJtbSI6MTAsInRvIjpmYWxzZSwidHMiOiJFbGV2YXRvciIsInRzeiI6MjksInRzcCI6MSwidGMiOiIjZmZmZmZmIiwidGYiOiInQmViYXMgTmV1ZScsIHNhbnMtc2VyaWYiLCJ0ZSI6IlNUUk9LRSIsInRmbCI6NTAsImdsIjoxLCJ3bCI6MCwibmwiOjB9",

    // Code 9 (Biohazard) - Ajout des guillemets et virgule
    "SLE8:eyJtIjoiRlgiLCJrIjozMjAwLCJ0IjowLCJoIjowLCJzIjoxMDAsInYiOjEwMCwiZCI6MTAwLCJmbSI6MzcsInNjIjo0LCJzcyI6NTAsInAxIjo1MCwicDIiOjUwLCJtbSI6OSwidG8iOmZhbHNlLCJ0cyI6IkVsZXZhdG9yIiwidHN6IjoyOSwidHNwIjoxLCJ0YyI6IiNmZmZmZmYiLCJ0ZiI6IidCZWJhcyBOZXVlJywgc2Fucy1zZXJpZiIsInRlIjoiU1RST0tFIiwidGZsIjo1MCwiZ2wiOjEsIndsIjoyLCJubCI6MH0=",

    // Code 10 (Lava) - Ajout des guillemets et virgule
    "SLE8:eyJtIjoiRlgiLCJrIjozMjAwLCJ0IjowLCJoIjowLCJzIjoxMDAsInYiOjEwMCwiZCI6MTAwLCJmbSI6MjYsInNjIjo0LCJzcyI6NTAsInAxIjo1MCwicDIiOjIyLCJtbSI6MTAsInRvIjpmYWxzZSwidHMiOiJFbGV2YXRvciIsInRzeiI6MjksInRzcCI6MSwidGMiOiIjZmZmZmZmIiwidGYiOiInQmViYXMgTmV1ZScsIHNhbnMtc2VyaWYiLCJ0ZSI6IlNUUk9LRSIsInRmbCI6NTAsImdsIjoyLCJ3bCI6MSwibmwiOjB9",

    // Code 11 (Binary) - Ajout des guillemets et virgule
    "SLE8:eyJtIjoiRlgiLCJrIjozMjAwLCJ0IjowLCJoIjowLCJzIjoxMDAsInYiOjEwMCwiZCI6MTAwLCJmbSI6MzUsInNjIjo0LCJzcyI6NTAsInAxIjoxMCwicDIiOjI4LCJtbSI6LTEsInRvIjpmYWxzZSwidHMiOiJFbGV2YXRvciIsInRzeiI6MjksInRzcCI6MSwidGMiOiIjZmZmZmZmIiwidGYiOiInQmViYXMgTmV1ZScsIHNhbnMtc2VyaWYiLCJ0ZSI6IlNUUk9LRSIsInRmbCI6NTAsImdsIjoyLCJ3bCI6MCwibmwiOjV9",

    // Code 12 (Club) - Ajout des guillemets et virgule
    "SLE8:eyJtIjoiRlgiLCJrIjozMjAwLCJ0IjowLCJoIjowLCJzIjoxMDAsInYiOjEwMCwiZCI6MTAwLCJmbSI6MTIsInNjIjo0LCJzcyI6NTAsInAxIjo2OCwicDIiOjcyLCJtbSI6OSwidG8iOmZhbHNlLCJ0cyI6IkVsZXZhdG9yIiwidHN6IjoyOSwidHNwIjoxLCJ0YyI6IiNmZmZmZmYiLCJ0ZiI6IidCZWJhcyBOZXVlJywgc2Fucy1zZXJpZiIsInRlIjoiU1RST0tFIiwidGZsIjo1MCwiZ2wiOjMsIndsIjowLCJubCI6MX0=",

    // Code 13 (Pure White) - Ajout des guillemets et virgule
    "SLE8:eyJtIjoiQ0NUIiwiayI6NjUwMCwidCI6MCwiaCI6MCwicyI6MTAwLCJ2IjoxMDAsImQiOjEwMCwiZm0iOjAsInNjIjo0LCJzcyI6NTAsInAxIjo1MCwicDIiOjUwLCJtbSI6OSwidG8iOnRydWUsInRzIjoiUHVyZSBXaGl0ZSIsInRzeiI6MjQsInRzcCI6MCwidGMiOiIjZmZmZmZmIiwidGYiOiInTW9ub3RvbicsIGN1cnNpdmUiLCJ0ZSI6IlNUUk9LRSIsInRmbCI6NTAsImdsIjoxLCJ3bCI6MSwibmwiOjB9",

    // Code 14 (Black or White) - Ajout des guillemets et virgule
    "SLE8:eyJtIjoiQ0NUIiwiayI6NjUwMCwidCI6MCwiaCI6MCwicyI6MTAwLCJ2IjoxMDAsImQiOjEwMCwiZm0iOjAsInNjIjo0LCJzcyI6NTAsInAxIjo1MCwicDIiOjUwLCJtbSI6NSwidG8iOnRydWUsInRzIjoiQmxhY2sgb3IgV2hpdGUiLCJ0c3oiOjE2LCJ0c3AiOjAsInRjIjoiIzAwMDAwMCIsInRmIjoiJ01vbm90b24nLCBjdXJzaXZlIiwidGUiOiJTVFJPS0UiLCJ0ZmwiOjUwLCJnbCI6MSwid2wiOjEwLCJubCI6MH0=",

    // Code 15 (Have Fun) - Ajout des guillemets (Dernier élément, virgule pas obligatoire mais conseillée)
    "SLE8:eyJtIjoiRlgiLCJrIjo2NTAwLCJ0IjowLCJoIjowLCJzIjoxMDAsInYiOjEwMCwiZCI6MTAwLCJmbSI6Mywic2MiOjQsInNzIjo1MCwicDEiOjQzLCJwMiI6MCwibW0iOjUsInRvIjp0cnVlLCJ0cyI6IkhhdmUgRnVuIiwidHN6IjoyNSwidHNwIjowLCJ0YyI6IiMwMDAwMDAiLCJ0ZiI6IidNb25vdG9uJywgY3Vyc2l2ZSIsInRlIjoiR0xJVENIIiwidGZsIjoxMDAsImdsIjoxLCJ3bCI6MSwibmwiOjB9"

];